# Generated by Django 4.1.7 on 2023-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=140)),
                ('telefone', models.CharField(max_length=14)),
                ('UF', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco_logradouro', models.CharField(max_length=100)),
                ('endereco_complemento', models.CharField(max_length=40)),
                ('dataNascimento', models.DateField()),
                ('dataMatricula', models.DateField()),
                ('numeroMatricula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('periodo', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('UF', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=140)),
                ('telefone', models.CharField(max_length=14)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco_logradouro', models.CharField(max_length=100)),
                ('endereco_complemento', models.CharField(max_length=40)),
                ('dataNascimento', models.DateField()),
                ('dataContratacao', models.DateField()),
                ('regimeContratacao', models.CharField(choices=[('temporario', 'Temporário'), ('clt', 'CLT'), ('pj', 'PJ')], max_length=20)),
            ],
        ),
    ]
