# Generated by Django 4.1.7 on 2023-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=2)),
                ('endereco_logradouro', models.CharField(max_length=100)),
                ('endereco_numero', models.CharField(max_length=40)),
                ('dataContratacao', models.DateField()),
                ('cursosLecionados', models.ManyToManyField(to='school_app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=2)),
                ('endereco_logradouro', models.CharField(max_length=100)),
                ('endereco_numero', models.CharField(max_length=40)),
                ('dataNascimento', models.DateField()),
                ('dataMatricula', models.DateField()),
                ('cursosCompletos', models.ManyToManyField(related_name='completos', to='school_app.curso')),
                ('cursosMatriculado', models.ManyToManyField(to='school_app.curso')),
            ],
        ),
    ]
