# Generated by Django 4.1.7 on 2023-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('dataMatricula', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='formularioCurso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursosCompletos',
            field=models.ManyToManyField(related_name='completos', to='school_app.curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursosMatriculados',
            field=models.ManyToManyField(to='school_app.curso'),
        ),
    ]
