# Generated by Django 4.1.7 on 2023-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_curso_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cursosCompletos',
            field=models.ManyToManyField(blank=True, related_name='completos', to='school_app.curso'),
        ),
    ]
